function RunMe_SSIPM

% Master file to organize simulations and results for Yamane et al.,
% submitted to Theoretical Ecology

% some options for choosing which blocks of code to run
do_1 = false;% sensitivity to length of pre-data burnin
do_2 = false; % determine how many simulations are needed for a consistent result
do_3 = false; % test effect of alternative prior distribution shapes on F
do_4 = false; % test for effect of process error in F
do_5 = false;
do_6 = false;
do_7 = true; % test for effect of autocorrelation in R
%--------------------------------------------------------
% Preliminary sensitivity runs based on reviewer comments
%--------------------------------------------------------
addpath 'fromWhiteetal2016'

% 1) Is 9 years of burn-in sufficient to reach a stable size distribution?
% To test this, look at one of the fits originally generated by Lauren.
% % This analysis does not appear in the final ms.
if do_1
test_burnin
end
%

% 2) How many replicate simulations are necessary to get a stable estimate
% of bias and SD in data?
% this uses pre-existing simulations that Lauren had done,
% SMYS_mockdata_F0.1ss200_12July2018 (in old_runs/)
% This analysis also does not formally appear in the final ms
if do_2
test_reps
end

% 3) Effect of the form of the prior on F
% This analysis is mentioned in the Methods but not formally presented
if do_3
test_prior(0)
end
%%%

% 4) Effect of the value of F (fixed in time)
if do_4
vary_F
analyze_vary_F(true) % do the post-processing
% figures are made in the Rmarkdown script
% These simulations are used for Fig. 2 in the text
end % end if do_4

% 5) Explore effect of process error in F on precision & bias
if do_5
process_error_F   % run the simulations
analyze_process_error_F(true) % do the post-processing & make figures
% These simulations are used for Fig. 3 in the text
end

% 6) Explore effects of less informative prior on R
if do_6
test_R_prior(0)
% These results are not included in the manuscript
end % end if do_6

% Effects of varying sample size per year
if do_7
vary_sample_size
analyze_vary_sample_size(true)%  do the post-processing
% figures are made in the Rmarkdown script - Figure 4a
end

% Effects of varying sample size per year
if do_8
vary_sample_years
analyze_vary_sample_years(true)%  do the post-processing
% figures are made in the Rmarkdown script - Figure 4b
end

if do_9
test_R_autocorr
analyze_test_R_autocorr
% These results appear in Online Supplement 4
end

